// <auto-generated />
namespace CraigsListClone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkingOnCategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkingOnCategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201703070407281_WorkingOnCategories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
